Android GUI: Downgrade commons-io to 2.5 because 2.6 depends on Java 8 features not available on Android
Process: com.github.chenxiaolong.dualbootpatcher.debug, PID: 17688
java.lang.NoSuchMethodError: java.io.File.toPath
    at org.apache.commons.io.FileUtils.isSymlink(FileUtils.java:3107)
    at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1616)
    at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
    at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
    at org.apache.commons.io.FileUtils.deleteQuietly(FileUtils.java:1648)
    at com.github.chenxiaolong.dualbootpatcher.patcher.PatcherUtils.extractPatcher(PatcherUtils.java:173)
    at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection.replaceViaSignedExec(MbtoolConnection.java:332)
    at com.github.chenxiaolong.dualbootpatcher.switcher.service.UpdateMbtoolWithRootTask.execute(UpdateMbtoolWithRootTask.java:53)
    at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.java:125)
    at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$1.run(ThreadPoolService.java:181)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)

Signed-off-by: Andrew Gunnerson <chenxiaolong@cxl.epac.to>